name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: helloNameTest
      id: hellonametest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: helloNameTest
        setup-command: ''
        command: gradle test --tests TestString1.helloNameTest
        timeout: 10
        max-score: 2
    - name: makeAbbaTest
      id: makeabbatest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: makeAbbaTest
        setup-command: ''
        command: gradle test --tests TestString1.makeAbbaTest
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLONAMETEST_RESULTS: "${{steps.hellonametest.outputs.result}}"
        MAKEABBATEST_RESULTS: "${{steps.makeabbatest.outputs.result}}"
      with:
        runners: hellonametest,makeabbatest
